-- MySQL Script generated by MySQL Workbench
-- Mon Jan  3 14:17:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`app_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`app_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`app_user` (
  `app_user_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  `disabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`app_user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`app_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`app_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`app_role` (
  `role_name` INT NOT NULL,
  `app_user_id` INT NOT NULL,
  PRIMARY KEY (`role_name`),
  INDEX `fk_app_role_app_user_idx` (`app_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_app_role_app_user`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `mydb`.`app_user` (`app_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`authors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`authors` (
  `idAuthor` INT NOT NULL,
  `author_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `idBooks` INT NOT NULL,
  `approval_status` TINYINT(1) NOT NULL,
  `book_title` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `publication_year` DATE NULL,
  `authors_idAuthor` INT NOT NULL,
  PRIMARY KEY (`idBooks`),
  INDEX `fk_books_authors1_idx` (`authors_idAuthor` ASC) VISIBLE,
  CONSTRAINT `fk_books_authors1`
    FOREIGN KEY (`authors_idAuthor`)
    REFERENCES `mydb`.`authors` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`app_user_has_books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`app_user_has_books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`app_user_has_books` (
  `app_user_id` INT NOT NULL,
  `idBooks` INT NOT NULL,
  `completion_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`app_user_id`, `idBooks`),
  INDEX `fk_app_user_has_books_books1_idx` (`idBooks` ASC) VISIBLE,
  INDEX `fk_app_user_has_books_app_user1_idx` (`app_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_app_user_has_books_app_user1`
    FOREIGN KEY (`app_user_id`)
    REFERENCES `mydb`.`app_user` (`app_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_app_user_has_books_books1`
    FOREIGN KEY (`idBooks`)
    REFERENCES `mydb`.`books` (`idBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
