@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiRWR3YXJkViIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjQxNzcwNzU2fQ.mWieEAdbSX-bmSGOdFSKmgJCcMEMycw2Z7v51umWLpU

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "AmyR",
  "password": "P@ssw0rd!"
}
###############################

GET http://localhost:8080/authorBooks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{

  "authorFirstName" : "Henry"

}